### ISSUE TITLE
CLI tool

### ISSUE THREAD

**Issue by creativewax** [StableCanvas/comfyui-client#1]
i have installed your cli tool, i can not get it to work at all, am i missing something?

**Comment by creativewax** [comment]
Got it working, needed a few more instructions i would say, i have noticed with more complex graphs like what i have is its breaking at points

**Comment by zhzLuke96** [comment]
you mentioned that the tool `breaking at points` when dealing with more complex graphs. Could you please provide more details on the specific issues you're encountering? This will help us better understand and address the problem.

and, You mentioned that you managed to get it working. Could you share what steps you took to resolve the initial issue? This information could be very helpful for us to include in the documentation for other users.

@creativewax  thx feedback!

**Comment by creativewax** [comment]
So to get it to work i had to use npx before it, not sure why

**Comment by creativewax** [comment]
But it would not work with the large graph i have, the order of nodes was messing up, so i had ChatGPT rewrite it a few times over and got to this, now builds the file but its not working because of custom nodes etc, i would of rewrote it myself but pushed on time today and didn't mind GPT hacking it together ha

**Comment by creativewax** [comment]
`#!/usr/bin/env node

const types = require("@babel/types");
const generator = require("@babel/generator").default;
const fs = require("fs");
const path = require("path");

const { Command } = require("commander");
const program = new Command();

const prettier = require("prettier");
const exifr = require("exifr");
const node_types = require("./comfyui.node.types.json");

function sanitizeClassName(className) {
  return className.replace(/[^a-zA-Z0-9_$]/g, '_');
}

function topologicalSort(nodes) {
  const sorted = [];
  const visited = {};
  const temp = {};

  function visit(nodeKey) {
    if (temp[nodeKey]) {
      throw new Error(`Circular dependency detected: ${nodeKey}`);
    }
    if (!visited[nodeKey]) {
      temp[nodeKey] = true;
      const node = nodes[nodeKey];
      if (node && node.inputs) {
        for (const inputKey in node.inputs) {
          const inputValue = node.inputs[inputKey];
          if (Array.isArray(inputValue)) {
            visit(inputValue[0]);
          }
        }
      }
      visited[nodeKey] = true;
      temp[nodeKey] = false;
      sorted.push(nodeKey);
    }
  }

  for (const nodeKey in nodes) {
    visit(nodeKey);
  }

  return sorted;
}

function generateCode(nodes) {
  if (!nodes || typeof nodes !== 'object') {
    throw new Error('Invalid nodes input');
  }

  const outputMap = {};
  const counter = {};

  const uniqueName = (name) => {
    counter[name] ||= 0;
    counter[name] += 1;
    return `${name}_${counter[name]}`;
  };

  const astNodes = [];

  const sortedNodeKeys = topologicalSort(nodes);
  console.log("Sorted Nodes Order:", sortedNodeKeys);

  for (const nodeKey of sortedNodeKeys) {
    const nodeValue = nodes[nodeKey];
    if (!nodeValue || !nodeValue.inputs || !nodeValue.outputs || !nodeValue.type) {
      throw new Error(`Invalid node data for nodeKey: ${nodeKey}`);
    }

    const inputs = nodeValue.inputs;
    const inputExpressions = Object.entries(inputs).map(
      ([inputKey, inputValue]) => {
        if (Array.isArray(inputValue)) {
          const refNodeKey = inputValue[0];
          const refOutputIndex = inputValue[1];
          const refVarName = outputMap[`${refNodeKey}_${refOutputIndex}`];

          if (!refVarName) {
            console.error(`Output map:`, outputMap); // Debugging output
            throw new Error(`Reference variable not found for inputKey: ${inputKey}, nodeKey: ${nodeKey}, refNodeKey: ${refNodeKey}, refOutputIndex: ${refOutputIndex}`);
          }

          return types.objectProperty(
            types.identifier(inputKey),
            types.identifier(refVarName)
          );
        } else {
          let val;
          switch (typeof inputValue) {
            case "string":
              val = types.stringLiteral(inputValue);
              break;
            case "number":
              val = types.numericLiteral(inputValue);
              break;
            case "boolean":
              val = types.booleanLiteral(inputValue);
              break;
            case "object":
              if (inputValue !== null) {
                throw new Error(`Invalid object input value for inputKey: ${inputKey}`);
              }
              val = types.nullLiteral();
              break;
            default:
              throw new Error(`Unsupported input value type for inputKey: ${inputKey}`);
          }
          return types.objectProperty(types.identifier(inputKey), val);
        }
      }
    );

    const inputObjectExpression = types.objectExpression(inputExpressions);
    const outputs = nodeValue.outputs;
    const outputIdentifiers = outputs.map((name, index) => {
      const varName = uniqueName(name);
      outputMap[`${nodeKey}_${index}`] = varName;
      return types.identifier(varName);
    });

    const leftArrayPattern = types.arrayPattern(outputIdentifiers);

    const sanitizedClassName = sanitizeClassName(nodeValue.type);
    const callExpression = types.callExpression(
      types.memberExpression(
        types.identifier("cls"),
        types.identifier(sanitizedClassName)
      ),
      [inputObjectExpression]
    );

    const variableDeclarator = types.variableDeclarator(
      leftArrayPattern,
      callExpression
    );
    const variableDeclaration = types.variableDeclaration("const", [
      variableDeclarator,
    ]);

    astNodes.push(variableDeclaration);
  }

  const codeFragments = astNodes.map((node) => generator(node).code);
  const generatedCode = codeFragments.join("\n");

  return generatedCode;
}

function loadNodesFromJsonFile(filename) {
  if (!fs.existsSync(filename)) {
    throw new Error(`File not found: ${filename}`);
  }

  const fileContent = fs.readFileSync(path.resolve(filename)).toString();
  let prompt;
  try {
    prompt = JSON.parse(fileContent);
  } catch (error) {
    throw new Error('Failed to parse JSON file');
  }

  if (!prompt) {
    throw new Error('Invalid JSON structure: Missing "prompt" key');
  }

  return convert_prompt_to_inner_nodes(prompt);
}

async function loadNodesFromImageFile(filename) {
  if (!fs.existsSync(filename)) {
    throw new Error(`File not found: ${filename}`);
  }

  const file = fs.readFileSync(path.resolve(filename));
  let params;
  try {
    params = await exifr.parse(file);
  } catch (error) {
    throw new Error('Failed to parse image metadata');
  }

  if (!params || !params.workflow) {
    throw new Error('Invalid image metadata: Missing "workflow" key');
  }

  let workflow;
  try {
    workflow = JSON.parse(params.workflow);
  } catch (error) {
    throw new Error('Failed to parse workflow from image metadata');
  }

  return convert_prompt_to_inner_nodes(workflow);
}

const convert_prompt_to_inner_nodes = (prompt) => {
  const types = node_types.properties;
  const nodes = {};

  const outputs_mapping = {};

  for (const [k, v] of Object.entries(prompt)) {
    if (!v || !v.class_type || !v.inputs) {
      throw new Error(`Invalid prompt node data for key: ${k}`);
    }

    const node = {
      type: v.class_type,
      inputs: v.inputs,
      outputs: [],
    };

    const schema = types[v.class_type];
    if (schema?.properties?.outputs?.items) {
      node.outputs = schema.properties.outputs.items.map((x) => x.type);
    }

    nodes[k] = node;

    for (const val of Object.values(v.inputs)) {
      if (!Array.isArray(val)) continue;
      const [nid, arg_idx] = val;
      outputs_mapping[nid] = Math.max(outputs_mapping[nid] ?? 0, arg_idx + 1);
    }
  }

  for (const [nid, max_len] of Object.entries(outputs_mapping)) {
    const node = nodes[nid];
    if (node.outputs.length >= max_len) {
      continue;
    }
    for (let arg_idx = 0; arg_idx < max_len; arg_idx++) {
      if (node.outputs[arg_idx]) continue;
      node.outputs[arg_idx] = `OUT_${arg_idx}`;
    }
  }

  return nodes;
};

const default_tpl = {
  esm: path.join(__dirname, "./tpls/esm.js"),
  cjs: path.join(__dirname, "./tpls/cjs.js"),
  web: path.join(__dirname, "./tpls/web.js"),
};

async function main() {
  program
    .name("nodejs-comfy-ui-client-code-gen")
    .description(
      "Use this tool to generate the corresponding calling code using workflow"
    )
    .version("0.8.0");

  program
    .option(
      "-t, --template [template]",
      "Specify the template for generating code, builtin tpl: [esm,cjs,web,none]",
      "esm"
    )
    .option(
      "-o, --out [output]",
      "Specify the output file for the generated code"
    )
    .option("-i, --in <input>", "Specify the input file, support .json file");

  program.parse();

  const {
    template: template_file,
    out: output_file,
    in: input_file,
  } = program.opts();

  if (!input_file) {
    console.error("ERR: input file is required");
    process.exit(1);
  }

  if (!input_file.match(/\.(json|png|jpg|jpeg)$/)) {
    console.error("ERR: input file must be a JSON, PNG, JPG, or JPEG file");
    process.exit(1);
  }

  let nodes;
  try {
    nodes = await (input_file.match(/\.(png|jpg|jpeg)$/)
      ? loadNodesFromImageFile(input_file)
      : loadNodesFromJsonFile(input_file));
  } catch (error) {
    console.error(`ERR: ${error.message}`);
    process.exit(1);
  }

  let generatedCode;
  try {
    generatedCode = generateCode(nodes);
  } catch (error) {
    console.error(`ERR: ${error.message}`);
    process.exit(1);
  }

  if (template_file && template_file !== "none") {
    const templatePath =
      default_tpl[template_file] ?? path.resolve(template_file);
    if (!fs.existsSync(templatePath)) {
      console.error(`ERR: Template file not found: ${templatePath}`);
      process.exit(1);
    }

    const templateContent = fs.readFileSync(templatePath, "utf-8");
    generatedCode = templateContent.replace(
      "/** CODE INJECTION HERE */",
      generatedCode
    );
  }

  try {
    generatedCode = await prettier.format(generatedCode, {
      parser: "babel",
      semi: true,
      singleQuote: true,
      trailingComma: 'all',
      printWidth: 80,
      tabWidth: 2,
    });
  } catch (error) {
    console.error(`ERR: Failed to format the generated code: ${error.message}`);
    process.exit(1);
  }

  if (output_file) {
    try {
      fs.writeFileSync(output_file, generatedCode);
      console.log(`Generated code has been saved to ${output_file}`);
    } catch (error) {
      console.error(`ERR: Failed to save the generated code: ${error.message}`);
      process.exit(1);
    }
  } else {
    console.log(generatedCode);
  }
}

main().catch((error) => {
  console.error(`ERR: ${error.message}`);
  process.exit(1);
});
`

**Comment by zhzLuke96** [comment]
> [generate.zip](https://github.com/user-attachments/files/15825214/generate.zip) But it would not work with the large graph i have, the order of nodes was messing up, so i had ChatGPT rewrite it a few times over and got to this, now builds the file but its not working because of custom nodes etc, i would of rewrote it myself but pushed on time today and didn't mind GPT hacking it together ha

Coooool, thanks for your code. I will review it shortly.

You mentioned that "custom nodes are causing issues"? It shouldn't be a problem with the code generated by the CLI, right? Because, in fact, within the client, there is no difference between built-in nodes and custom nodes in ComfyUI, as they are the same in terms of interfaces.

If you are referring to the process from code to graph, I haven't implemented that part yet. It belongs to the `TODOs` section. One major reason is that it requires implementing the scheduling logic for nodes within the ComfyUI system (i.e., the sort logic).

**Comment by zhzLuke96** [comment]
add

548f97dc279ff207e38a55f6ab63b81066d63076
499426731b5580b3130fbf5d982b3537a71fa6f9
4199047171cc8efab9f32d19b9a6d08f72d99119
15c467791a93e89c2b1632cf237f45f648525675
7ba10847d3995040e260b098b7d8ddb982e57e94
63b0d6e162c9ec532fd2aed184dd127c143fb1e3
