### ISSUE TITLE
CLI: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by jelling** [StableCanvas/comfyui-client#8]
**Describe the bug**

CLI tool throws `Cannot use import statement outside a module`

**To Reproduce**

Issue happened with multiple different ways of running the tool.

With an npm script:

```
  "scripts": {
    "foo": "tsx node_modules/@stable-canvas/comfyui-client-cli/src/main-cli.ts -- "
  }
```

And:

```
npm run foo ./latent-vision.attention-masking.json -t none
```

Even with `package.json` set to module:

```
  "type": "module",
```

I had the same issue when running wth `npx` as [another user mentioned having to do](https://github.com/StableCanvas/comfyui-client/issues/1#issuecomment-2166128292).

**Workaround**

It worked when I used `tsx` to run the underlying source code like this:

```
tsx node_modules/@stable-canvas/comfyui-client-cli/src/main-cli.ts -i example.json -t none
```

**Comment by zhzLuke96** [comment]
fixed https://github.com/StableCanvas/comfyui-client/commit/3e15a1bb82d311a2c6242db236d518f97ea3f9a3

Now precompiled, no longer depends on ts-node or tsx
